<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Управление полями формы "{{ $form->name }}"</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        function transliterate(text) {
            const ru = {
                'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 
                'е': 'e', 'ё': 'e', 'ж': 'zh', 'з': 'z', 'и': 'i', 
                'й': 'y', 'к': 'k', 'л': 'l', 'м': 'm', 'н': 'n',
                'о': 'o', 'п': 'p', 'р': 'r', 'с': 's', 'т': 't',
                'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'ts', 'ч': 'ch',
                'ш': 'sh', 'щ': 'sch', 'ъ': '', 'ы': 'y', 'ь': '',
                'э': 'e', 'ю': 'yu', 'я': 'ya'
            };

            return text.toLowerCase().split('').map(char => {
                return ru[char] || char;
            }).join('').replace(/[^a-z0-9_]/g, '_').replace(/_+/g, '_');
        }

        // Функция для автоматической генерации кода поля из имени
        function updateFieldName() {
            const labelInput = document.getElementById('fieldLabel');
            const nameInput = document.getElementById('fieldName');
            
            // Генерируем код поля только если он пустой или был автоматически сгенерирован
            if (nameInput.value === '' || nameInput.dataset.autoGenerated === 'true') {
                nameInput.value = transliterate(labelInput.value);
                nameInput.dataset.autoGenerated = 'true';
            }
        }

        document.getElementById('fieldLabel').addEventListener('input', function() {
            updateFieldName();
        });

        // Когда пользователь вручную меняет код поля, отключаем автогенерацию
        document.getElementById('fieldName').addEventListener('input', function() {
            this.dataset.autoGenerated = 'false';
        });

        document.getElementById('fieldName').addEventListener('blur', function() {
            checkUniqueness(this, 'name');
        });

        document.getElementById('fieldLabel').addEventListener('blur', function() {
            checkUniqueness(this, 'label');
        });

        async function checkUniqueness(input, field) {
            const formId = '{{ $form->id }}';
            const value = input.value;
            
            try {
                const response = await fetch(`/api/forms/${formId}/fields/check-unique?field=${field}&value=${encodeURIComponent(value)}`);
                const data = await response.json();
                
                const errorDiv = input.nextElementSibling;
                if (!data.unique) {
                    input.classList.add('border-red-500');
                    if (!errorDiv || !errorDiv.classList.contains('text-red-500')) {
                        const error = document.createElement('div');
                        error.className = 'text-red-500 text-sm mt-1';
                        error.textContent = `Это ${field === 'label' ? 'название' : 'имя'} уже используется`;
                        input.parentNode.insertBefore(error, input.nextSibling);
                    }
                } else {
                    input.classList.remove('border-red-500');
                    if (errorDiv && errorDiv.classList.contains('text-red-500')) {
                        errorDiv.remove();
                    }
                }
            } catch (error) {
                console.error('Ошибка при проверке уникальности:', error);
            }
        }

        function updateLabel() {
            const nameInput = document.getElementById('fieldName');
            const labelInput = document.getElementById('fieldLabel');
            
            // Если метка пустая, используем значение из поля имени
            if (labelInput.value === '') {
                labelInput.value = nameInput.value;
            }
        }

        // Функция для транслитерации имени поля
        function transliterateName() {
            const nameInput = document.getElementById('fieldName');
            nameInput.value = transliterate(nameInput.value);
        }

        document.getElementById('fieldName').addEventListener('input', function() {
            updateLabel();
        });

        document.getElementById('fieldName').addEventListener('blur', function() {
            checkUniqueness(this, 'name');
        });

        document.getElementById('fieldLabel').addEventListener('blur', function() {
            checkUniqueness(this, 'label');
        });
    </script>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto px-4 py-8">
        <div class="flex justify-between items-center mb-8">
            <div>
                <h1 class="text-3xl font-bold">Управление полями формы</h1>
                <p class="text-gray-600 mt-2">{{ $form->name }}</p>
            </div>
            <div class="space-x-4">
                <a href="{{ route('forms.index') }}" class="bg-gray-500 text-white px-4 py-2 rounded-md hover:bg-gray-600">
                    К списку форм
                </a>
                <a href="{{ route('forms.show', $form) }}" class="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700">
                    Просмотр формы
                </a>
                <a href="{{ route('forms.submissions', $form) }}" class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
                    Результаты
                </a>
            </div>
        </div>

        @if(session('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4">
                {{ session('success') }}
            </div>
        @endif

        <!-- Форма создания поля -->
        <div class="bg-white rounded-lg shadow-md p-6 mb-8">
            <h2 class="text-xl font-semibold mb-4">Добавить новое поле</h2>
            <form action="{{ route('forms.fields.store', $form) }}" method="POST">
                @csrf
                @if ($errors->any())
                    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
                        <ul class="list-disc list-inside">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Имя поля</label>
                        <input type="text" 
                               id="fieldLabel"
                               name="label" 
                               class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 @error('label') border-red-500 @enderror" 
                               required
                               value="{{ old('label') }}">
                        <p class="text-sm text-gray-500 mt-1">Отображаемое название поля</p>
                        @error('label')
                            <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Код поля</label>
                        <div class="flex gap-2">
                            <input type="text" 
                                   id="fieldName"
                                   name="name" 
                                   class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 @error('name') border-red-500 @enderror" 
                                   required
                                   value="{{ old('name') }}"
                                   data-auto-generated="true">
                            <button type="button" 
                                    onclick="transliterateName()" 
                                    class="px-3 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300"
                                    title="Транслитерировать в латиницу">
                                Aa
                            </button>
                        </div>
                        <p class="text-sm text-gray-500 mt-1">Генерируется автоматически из имени поля</p>
                        @error('name')
                            <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                        @enderror
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Тип поля</label>
                        <select name="type" class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500" required>
                            <option value="text">Текстовое поле</option>
                            <option value="textarea">Многострочное поле</option>
                            <option value="select">Выпадающий список</option>
                            <option value="checkbox">Флажок</option>
                            <option value="radio">Радиокнопка</option>
                            <option value="date">Дата</option>
                            <option value="time">Время</option>
                            <option value="number">Число</option>
                        </select>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Порядок сортировки</label>
                        <input type="number" name="sort_order" value="0" class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Обязательное поле</label>
                        <input type="checkbox" name="required" value="1" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Справочник (для select/radio/checkbox)</label>
                        <select name="dictionary_id" class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                            <option value="">Не использовать справочник</option>
                            @foreach($dictionaries as $dictionary)
                                <option value="{{ $dictionary->id }}">{{ $dictionary->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="md:col-span-2">
                        <label class="block text-sm font-medium text-gray-700 mb-2">Опции (для select/radio/checkbox, каждая опция с новой строки)</label>
                        <textarea name="options" rows="3" class="w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></textarea>
                    </div>
                </div>

                <div class="mt-4">
                    <button type="submit" class="bg-indigo-600 text-white px-4 py-2 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                        Добавить поле
                    </button>
                </div>
            </form>
        </div>

        <!-- Список существующих полей -->
        <div class="bg-white rounded-lg shadow-md p-6">
            <h2 class="text-xl font-semibold mb-4">Существующие поля</h2>
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead>
                        <tr>
                            <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Имя</th>
                            <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Код</th>
                            <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Тип</th>
                            <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Обязательное</th>
                            <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Действия</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach($fields as $field)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $field->label }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $field->name }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $field->type }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">{{ $field->required ? 'Да' : 'Нет' }}</td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <a href="{{ route('forms.fields.edit', [$form, $field]) }}" class="text-indigo-600 hover:text-indigo-900 mr-3">Редактировать</a>
                                    <form action="{{ route('forms.fields.destroy', [$form, $field]) }}" method="POST" class="inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="text-red-600 hover:text-red-900">Удалить</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html> 